### ISSUE TITLE
when closing a case - move it to my case and remove from open cases

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#14]
without the need for a reload. 
move it after 10 seconds, and leave a ghost for a few seconds so the user can regret closing the case

**Comment by noam-honig** [comment]
לא הבנתי :)

**Comment by aviad-yedidim** [comment]
כרגע כשאני סוגר קריאה היא עדין מופיעה בקריאות שלי עד שארענן את העמוד
השאלה אם אפשר ש10 שניות אחרי הסגירה האירוע יעבוד לאירועים שלי. כדי שיוכלו 'להחיות' אותו אם בטעות סגרו - הקריאה תישאר לעוד 10 שניות כמו רוח רפאים - שהיא פשוט הרבה יותר בהירה ל10 שניות ולחיצה עליה מציגה אותה

**Comment by aviad-yedidim** [comment]
מספיק שולי כדי לא לטפל
