### ISSUE TITLE
display the notes that the user wrote

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#16]
only to the user who wrote and to dispatcher and admin

**Comment by noam-honig** [comment]
You can see them in the history - isn't that enough?
![image](https://github.com/noam-honig/trempim/assets/16635859/1a7d1177-50fe-4669-ab43-f709a6deb69c)

**Comment by aviad-yedidim** [comment]
Is it possible that it wasn't that way earlier?
Its exactly ehat i want
