### ISSUE TITLE
limit user up to 5 new cases taken an hour

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#17]

**Comment by noam-honig** [comment]
Do you want to limit him to only have 5 cases at a time - or only register to 5 cases in an hour (even if he returned a few and taken them again

I think this could be problematic - we do record everything, so we'll be able to find foul play

**Comment by aviad-yedidim** [comment]
The second option. If someone takes and returns cases - it's a problem. 
Also, can it create some kind of alert to the managers? When they log the next time

**Comment by aviad-yedidim** [comment]
correction - both.
don't allow more than 5 at a time
and limit to 7 per hour - take and return count as a take
