### ISSUE TITLE
add map

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#22]
pin the departure point
pin the destination as a ghost when the user selects departure and zoom to show both
optional - show the rout

**Comment by noam-honig** [comment]
היום כאשר הUSER לוחץ על מפה - זה פותח לו את אפליקצית המפה עם זה - זה לא מספיק טוב?

**Comment by aviad-yedidim** [comment]
בשלב V3 הייתי אומר גם להציג על המפה את מסלול הנסיעה המתוכנן שלו בלי קשר, ולראות שינועים על הדרך...
