### ISSUE TITLE
Add Until When to case

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#27]
The dispatcher needs to write down how many hours is the case relevant or until what hour it's relevant. The case will show the calculated time and date of when the case is relevant. 
There will be a status 'timed out' cases in yellow, the dispatcher will need to review and see if to close or to change the due time.

**Comment by noam-honig** [comment]
![image](https://github.com/noam-honig/trempim/assets/16635859/2cd00523-765c-4a24-96f1-27efb985755f)

**Comment by aviad-yedidim** [comment]
מעולה
