### ISSUE TITLE
לתמוך בהזנת מספר בתבנית +972 53-555-5559

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#31]
בנוסף, גם בחיפוש מספר להמיר את התבנית כמו בהזנת מספר חדש

**Comment by noam-honig** [comment]
1. עשיתי את זה כדי שלא יהיה מצב שאותו אדם רשום פעמיים עם שני מספרי טלפון - ואני חושב שזה גם מבלבל שיש את שתי האופציות

תסביר לי עוד קצת את הצורך

**Comment by aviad-yedidim** [comment]
אם אני מזין מספר בתבנית הזאת, המערכת תשנה אותו למספר ללא מקפים ועם 0 בהתחלה, כך שיהיה תואם את התבנית 'ל מספרי הטלפון של המשתמשים

**Comment by aviad-yedidim** [comment]
already exist
