### ISSUE TITLE
Add search bar for dispatcher to search for a specific case

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#33]

**Comment by noam-honig** [comment]
What are the fields you would like them to search on?

**Comment by aviad-yedidim** [comment]
Header
Phone number
From address
To address
Filter by status

**Comment by noam-honig** [comment]
In the all rides screen, on the top of every column, you can filter by that column:
![image](https://github.com/noam-honig/trempim/assets/16635859/0ea48c23-55de-48f0-87fe-57a9fedbeae1)

Also - you can filter by clicking on the grid menu and selecting filter:
![image](https://github.com/noam-honig/trempim/assets/16635859/20ff48f2-498c-4c0d-9448-ffb40871f92b)
