### ISSUE TITLE
Add automatic ID to the case

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#36]
מספר רץ
אחרי שנסיים את כל הטיוטות והעלויה לאויר

**Comment by noam-honig** [comment]
הוספתי מספר רץ - התחלתי מ3000 כדי שלא יהיה כפילות:
![image](https://github.com/noam-honig/trempim/assets/16635859/5fa03e6c-e2e7-4875-bfbf-9969c0b7f21c)
