### ISSUE TITLE
Jump when opening a case as a dispatcher

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#38]
When opening a case as a dispatcher the system opens the case as a driver and then jumps and opens the case as a dispatcher

**Comment by noam-honig** [comment]
Fixed

**Comment by aviad-yedidim** [comment]
Still happening

**Comment by noam-honig** [comment]
Please refresh and test.
If still persists - send me a short video on whatsapp so I'll understand what you mean

**Comment by aviad-yedidim** [comment]
https://github.com/noam-honig/trempim/assets/148071554/13f4923e-804a-47e6-87e1-be1297a97279

**Comment by noam-honig** [comment]
Yes - it's because it is loading the phones, and then you can see them - I recommend to leave it at that - or you ok with that?

**Comment by aviad-yedidim** [comment]
Yes
