### ISSUE TITLE
in 'my cases' the color adds only after going to another tab

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#42]
https://github.com/noam-honig/trempim/assets/148071554/2d0cc0dc-5e3b-4582-871d-f961728af123

**Comment by noam-honig** [comment]
I thought that the color is meaningless in the volunteer screen - it's only meaningful in the search screen - and when you leave the tab and come back - I remove the trip from the search screen.

That short flicker is crutial?
