### ISSUE TITLE
dispatcher - default sort

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#47]
1. show all the statuses except for done and irrelevant
2. show in the following order:
> a. has an issue
> b. in delivery
> c. open

make has an issue stand out. maybe color the row red

**Comment by noam-honig** [comment]
קודם כל בוא נעביר לעברית - קשה לי עם זה:)
באיזה מסך (במסך חיפוש נסיעה או מסך אחר?)
ונגיד שיש כזה עם ISSUE שהוא מצא - איך זרימת הטיפול בזה אמורה להיות?
אקיצור - שיחונת תעזור פה

**Comment by aviad-yedidim** [comment]
במסך כל הנסיעות
סינון ברירת המחדל יהיה לפי הקטגרויה:
1. יציג רק את מה שלא סגור/לא רלוונטי
2. יציג קודם את האירועים שיש להם בעיה, אחר כך את האירועים שנלקחו ואז את האירועים הפנויים.

את הנסיעות עם בעיה לסמן בולט - אולי את כל השורה באדום.

מוקדן שרואה את השורה עם הבעיה קורה את ההערה, מתקשר לנהג, מבין מה הסיפור ומטפל - ואז מחזיר את האירוע להיות פעיל או סוגר אותו כלא רלוונטי.

**Comment by noam-honig** [comment]
בוצע:
![image](https://github.com/noam-honig/trempim/assets/16635859/fa421a01-0c67-4c0e-b834-4ea02db6c7be)

כדי להציג הכל, לחץ הצג הכל בתפריט בצד ימין למעלה
