### ISSUE TITLE
להזיז את מזהה הקריאה בתצוגה ללמטה

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#48]
![17-10-2023 11-54-44](https://github.com/noam-honig/trempim/assets/148071554/4e1e36ec-41ee-41ae-ab3c-dbe58cd98470)
שמספר הקריאה יהיה באפור ולא בשחור, ויוצג בחלק התחתון - בין היום (17/10)-8:00 לבין לפרטים והרשמה

**Comment by aviad-yedidim** [comment]
amazing
instead of מספר change to שינוע מספר

**Comment by aviad-yedidim** [comment]
![image](https://github.com/noam-honig/trempim/assets/148071554/ce016145-bf45-4efa-9df9-aa2a7023317d)
still

**Comment by noam-honig** [comment]
![image](https://github.com/noam-honig/trempim/assets/16635859/b8d67364-926a-4896-abca-cf358aad7e87)
