### ISSUE TITLE
Allow shift manager to return irrelevant case to active

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#61]

**Comment by aviad-yedidim** [comment]
![image](https://github.com/noam-honig/trempim/assets/148071554/014feebd-3eca-4bc3-9004-6076506ae943)
success
but a new bug - does not show in the 'find case' tab
![image](https://github.com/noam-honig/trempim/assets/148071554/bbb0c1e0-1d22-4607-bb42-ab8b534066cb)

**Comment by noam-honig** [comment]
תוקן עוד אתמול - היה באג שעדכון כזה גרם למשימה להפוך להיות טיוטא ולכן לא מצאת אותה - תיקנתי את זה.

מתחיל לחשוב שאולי כדאי שטיוטא יהפוך להיות סטטוס ולא שדה נפרד - מה אתה אומר? (תענה בווטסאפ כדי שאראה בזמן קצר)

**Comment by aviad-yedidim** [comment]
מקובל
