### ISSUE TITLE
When trying to add new user with existing phone, allow to edit the existing user

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#69]
![IMG-20231018-WA0124.jpg](https://github.com/noam-honig/trempim/assets/148071554/21d2f1df-a307-400a-a9ff-6cf16de3c1ff)

From here I want to just update the user. In the current situation I need to manually search the phone number to get to the user to edit.

**Comment by noam-honig** [comment]
Now start with the search by phone or number - and if not found, it'll be the default when you click on new user
