### ISSUE TITLE
Add the option to deny a draft

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#70]
Today there is only option to make it irrelevant
I want an option to deny

**Comment by noam-honig** [comment]
Added it

**Comment by aviad-yedidim** [comment]
When moving the draft to be irrelevant, the button to the left says 'בטל אישור'
![Screenshot_2023-10-24-20-42-04-487_com.android.chrome.jpg](https://github.com/noam-honig/trempim/assets/148071554/2c560db1-0d89-467d-9b2f-e41428c46253)
