### ISSUE TITLE
When filtering old cases by irrelevant, shows nothing

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#72]
![IMG-20231018-WA0128.jpg](https://github.com/noam-honig/trempim/assets/148071554/0fc4d44c-578a-46a7-b887-683380cef986)

Only after clicking on the three dots on the right corner and changing to view all cases, only then it shows the cases. 
Need that the system will cancel the default filter, if applying a filter on status.

**Comment by noam-honig** [comment]
You've asked that by default this screen will only show relevant tasks - to see non relevant tasks, you need to first click on Show All tasks on the grid menu, and then you'll be able to search by non relevant

![image](https://github.com/noam-honig/trempim/assets/16635859/7b6bf3ba-ce49-458b-baf0-757b71fc2e19)
