### ISSUE TITLE
Add to the dispatcher name, their phone number in the ability to contact them. 

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#74]
Add everywhere these dispatcher name their number and the ability to contact them
Case history, draft, all cases. 
Of course only allow shift manager or manager to see the contact information of the dispatcher.

**Comment by noam-honig** [comment]
![image](https://github.com/noam-honig/trempim/assets/16635859/0c9a8b85-8ea3-4e2d-a0fe-8d4b98b741fd)
