### ISSUE TITLE
Export open cases from selected District to WhatsApp

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#88]
Need to select from district, to district or both, and select district. 
The output will be text (with a button to share in WhatsApp):

(Note - The * and _ needed for highlighting the text in WhatsApp)

Header:
*_10 קריאות פתוחות {אל/מ}- אשדוד / מושבי אשדוד - שעה 17:00_*
תבנית
*_ (מספר קריאות) קריאות פתוחות {אם נבחר אל/מ - להוסיף} (שם המחוז) - (שעת הפקה - מעוגל ל10 דקות)_*

List:
▪️שינוע כמה חפצים מאשדוד אל קיבוץ דפנה מס-1179
▪️שינוע מישקפיים ושקית גומי מאשדוד אל מחנה אורים מס-1173
▪️שינוע חייל מחולון אל מושב עזריקם מס-1201
תבנית
▪️שינוע (כותרת) מ(מקור) אל (יעד) מס' - (מספר קריאה)

Take only relevant cases - in relevant status and the time from has past (do not add future cases)

**Comment by noam-honig** [comment]
Do you also want a link so they can see the task directly?

**Comment by aviad-yedidim** [comment]
Great idea!
After every roe the link to the specific task

**Comment by aviad-yedidim** [comment]
got cases from all the country, when there is only one case that answers my search

![image](https://github.com/noam-honig/trempim/assets/148071554/bb3b5f11-609a-4d0f-ac61-9cb6bb93e49e)

קריאות פתוחות מאזור מרכז לאזור דרום  - שעה 12:50 ( 11 קריאות) :

**Comment by aviad-yedidim** [comment]
עובד מעולה לשלב הזה.
תיקונים קטנים:
קריאות פתוחות  - שעה 9:31 ( 6 קריאות) : 
* שינוע רכב: שינוע רכב של חייל מילואים  מספסופה לפדואל (3765)
https://shinua.yedidim1230.com/t........
לתקן רווחים בכותרת (רווח כפול אחרי המילה פתוחות), (רווח כפול אחרי המילה שעה), (רווח אחרי הסוגריים של כמות הקריאות), (רווח אחרי הסוגריים ולפני הנקודותיים)
להעביר את ה* בתחילת של השורה (במילה שינוע) ללפני מספר הקריאה, ולהוסיף * בסוף השורה - ככה לעשות הדגשה. כלומר, * כוכביות בכל שורה, לפני ואחרי הסוגריים של מספר הקריאה

**Comment by aviad-yedidim** [comment]
יותר טוב, עדין אשמח אם אפשר לעגל את השעה ל10 דקות הקרוב (21:00, 21:10, 21:20 וכן הלאה)
בנוסף שתי הערות:
1. אפשר בטעות לייצא את 'הנסיעות שלי' וזה יוצא עם הכיתוב קריאות פתוחות
2. אם מנסים לייצא עם 0 קריאות יוצא מלל קצת מצחיק - "קריאות פתוחות מאזור תל אביב - שעה 21:56 (0 קריאות): "
לגבי שאר הדברים שכתבתי לפני כן - לא מספיק חשוב כדי שיהיה שווה את ההתעסקות

**Comment by noam-honig** [comment]
Fixed
