### ISSUE TITLE
add relevance check process

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#89]
יש קבוצה שפתחו עם כמה חבר'ה שעושים את הטלפונים לבדוק האם רלוונטי.
מאז שעברו למערכת הנושא התמסמס - 
היה להם תהליך עבודה עם האקסל שהם ידעו מה לעשות, וקצת הסתבכו עם המערכת...
כרגע הנחיתי את האחראי איך להוריד אקסל, והם יעשו בדיקות מאקסל.
אשמח אם תוכל לחשוב על דרך שצוות בדיקות יוכל לעבוד במערכת ולסמן אחד לשני מה הם בדקו ומה לא.
מעדיף שאלו יהיו משתמשים עם הרשאות מינימליות ככל האפשר, לרוב לוקחים חבר'ה צעירים למשימות כאלו, ואני לא רוצה לתת להם כוח במערכת.
_נועם - אתה רוצה גם שהם יוכלו לעדכן פרטים? או לכתוב הערה לאחמש?_
או לסגור כלא רלוונטי, או להשאיר הערה - ולהעביר למצב 'יש בעיה' שאחמש יסתכל על זה. 
אפשר הכי בקלות פשוט להסיר ממוקדן חרבות את המגבלה השעתית, שייקח את הקריאות על עצמו ויעביר לסטטוס הנכון. 
רק צריך יהיה כפתור 'בדקתי - רלוונטי' שישאיר חותמת זמן מתי נבדק. 
ואפשרות לסדר לפי זמן בדיקה, כאשר זמן פתיחת האירוע = זמן בדיקה ראשונה.

**Comment by aviad-yedidim** [comment]
1. לעשות סטטוס 'בדיקת רלוונטיות'
2. לעשות אפשרות לנעילת טיוטא/בדיקת רלוונטיות על שם של אחמש, כך שלא יצטרך להיות על הקריאה עצמה בזמן הבדיקה.
3. לוגיקת העברה לסטטוס לא רלוונטי ולסטטוס בדיקת רלוונטיות:
שינוע חיילים אחרי 12 שעות יהפכו ללא רלוונטי
ושינוע ציוד יעבור אחרי 24 שעות לבדיקת רלוונטיות

**Comment by noam-honig** [comment]
את סעיף 2, עשיתי.

**Comment by noam-honig** [comment]
@aviad-yedidim 
תנסח בדיוק את הFLOW של מה שאתה רוצה שהם יעשו (או דבר איתי על זה בשיחה)

**Comment by aviad-yedidim** [comment]
שינוי בבקשה שלנו:
כל הקריאות שנפתחו עד השעה 22:00 בערב, יעברו בבוקר למחרת ב6:30 לסטטוס בדיקת רלוונטיות (או טיוטה),
למעט:
קריאות שינוע חיילים יעברו 24 אחרי מועד תחילת הרלוונטיות שלהן ל'לא רלוונטי'. כלומר התוקף שלהן הוא 24 שעות בלבד.
קריאות שינוע רכב - נשארות פתוחות.

מבחינת ה'בדיקת רלוונטי' - התנהגות בדיוק כמו טיוטה, אבל שיהיה הפרדה בניהם בכותרת שמי שמטפל ידע שזה בדיקה ולא טיוטה
