### ISSUE TITLE
Open by default search for a case and not my cases

### ISSUE THREAD

**Issue by aviad-yedidim** [noam-honig/trempim#97]
When opening the system by default open the tab search for a case

**Comment by noam-honig** [comment]
אני לא בטוח שזה נכון - נהג שנכנס פעם שנייה רוצה לראות את המשימות שכבר יש לו.
אם אין לו משימות זה עובר לחיפוש אוטומטית
אני חושב שעכשיו כשאני לא מציג משימות לא פעילות לנהג - וכך אם אין לו משימות זה יעבור אוטומטית לחיפוש - אני חושב שזה מספיק
